### ISSUE TITLE
UCP color complaint

### ISSUE THREAD

**Issue by BryanBoru** [TFT8/Uniforms#5]
We've have the comment on steam as well as two CS members complain of UCPs monochromatic coloring, they feel it should have a slightly greenish tint, not so gray.  As seen on [wikipedia](https://en.wikipedia.org/wiki/Universal_Camouflage_Pattern#Color_selection), UCP has a mix of tan, green and gray. Ours is mostly light tan and gray.  I will try to make some attempts to improve.

**Comment by theYoursTruly** [comment]
Give it to people that made the complaint (only the flat texture) and make them "fix it". I feel like it's all personal preference + Arma coloring + monitor + graphical settings. It's all subjective.

**Comment by BryanBoru** [comment]
I can normally agree that color is subjective, but for two separate people to hold the opinion we should at least try to see if we can address it with some simplicity.
